project:
  type: website

website:
  title: "Yichao.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: cv.pdf
        text: CV
      - text: Assignments
        menu:
         - href: assignment1.qmd
           text: assignment1
         - href: assignment2.qmd
           text: assignment2
         - href: assignment3.qmd
           text: assignment3
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

